#!/usr/bin/python
import os, sys, imp
 
try:
   os.environ['DJANGO_SETTINGS_MODULE'] = 'kfimember.settings'
   sys.path.append(os.path.join(os.environ['OPENSHIFT_REPO_DIR'], 'wsgi', 'kfimember'))
 
   zvirtenv = os.path.join(os.environ['OPENSHIFT_PYTHON_DIR'],
                           'virtenv', 'bin', 'activate_this.py')
   exec(compile(open(zvirtenv).read(), zvirtenv, 'exec'),
        dict(__file__ = zvirtenv) )
except IOError:
   pass
 
from django.core.handlers import wsgi
application = wsgi.WSGIHandler()